# Build stage
FROM node:18 as build

WORKDIR /frontend

COPY ./frontend /frontend

RUN npm install

RUN npm run build

FROM nginx:alpine

COPY --from=build /frontend/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
